title: Light Slides
author: Buchanan Kerswell
email: buchanankerswell@u.boisestate.edu
baseurl: /light-slides # the subpath of your site, e.g. /blog
url: https://buchanankerswell.github.io # the base hostname & protocol for your site
description: >-
  A simple catalogue of petrographic thin sections in plane- and cross-polarized light. Videos thanks to <a href="https://www.youtube.com/playlist?list=PL8dDgAwuMuPTXCj0MPO_G6jTz4pzXVcZi">Matt Kohn</a>, Boise State University.
tagline: "A random sampling of thin sections from Matt Kohn's library"
social:
  name: Buchanan Kerswell
  links:
    - https://github.com/buchanankerswell
    - https://www.researchgate.net/profile/Buchanan_Kerswell
    - https://scholar.google.com/citations?hl=en&user=O7TM22kAAAAJ
    - https://orcid.org/0000-0003-0495-4162
    - https://osf.io/sd5z3/
  github_url: "https://github.com/buchanankerswell"
  researchgate_url: "https://www.researchgate.net/profile/Buchanan_Kerswell"
  googlescholar_url: "https://scholar.google.com/citations?hl=en&user=O7TM22kAAAAJ"
  orcid_url: "https://orcid.org/0000-0003-0495-4162"
  osf_url: "https://osf.io/sd5z3/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
collections:
  slides:
    output: true
